### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by hasanelfalakiy** [Kotlin-Language-Server/kotlin-language-server#12]
can this kotlin lsp be used in sora editor?

**Comment by Zerumi** [comment]
Hi! We assume that every code editor supports [Language Server Protocol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) will support KLSP as well.
But there are some issues, because this project are now "under heavy development", so even in VSCode we don't have significant stable results, but we are working on it.

**Comment by hasanelfalakiy** [comment]
> Hi! We assume that every code editor supports [Language Server Protocol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) will support KLSP as well.
> But there are some issues, because this project are now "under heavy development", so even in VSCode we don't have significant stable results, but we are working on it.
> 
> Leave some questions, if you have, or just close this issue. Thanks!

okay, if there are any other questions I will post them here, thank you
